version: '3'
services:
    service_a:
      build: ./services
      ports:
        - "3000:3000"
      networks:
        apisix:
        
    apisix:
      image: apache/apisix
      restart: always
      volumes:
        - ./apisix/conf/config.yml:/usr/local/apisix/conf/config.yaml:ro
      depends_on:
        - etcd
      ports:
        - "9080:9080/tcp"
        - "9091:9091/tcp"
        - "9443:9443/tcp"
        - "9092:9092/tcp"
      networks:
        apisix:
    
    apisix-dashboard:
      image: apache/apisix-dashboard
      restart: always
      volumes:
        - ./apisix/dashboard/config.yml:/usr/local/apisix-dashboard/conf/conf.yaml
      ports:
        - "9000:9000"
      networks:
        apisix:
    
    etcd:
      image: bitnami/etcd
      volumes:
        - etcd_data:/bitnami/etcd
      environment:
        ETCD_DATA_DIR: /bitnami/etcd
        ETCD_ENABLE_V2: "true"
        ALLOW_NONE_AUTHENTICATION: "yes"
        ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
        ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ports:
        - "2379:2379/tcp"
      networks:
        apisix:

volumes:
  db-data:
  etcd_data:
    driver: local

networks:
  apisix:
    driver: bridge